# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: ""

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when running locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: ""

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: ""

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hack New Haven | 9-10 November 2024"
  description: ""
  image:       "./images/favicon.png"
# Event information.
event:
  name:        "Hack New Haven"
  description: "Reach for the Stars"
  date:        "9-10 November, 2024"
  location:    "West Haven, CT, United States"

  # trust_badge:
  #   year:   "2017"  # season year
  #   region: "eu"    # "na" or "eu"
  #   color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Submit"
        my_mlh:
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:yejar1@unh.newhaven.edu"

  about:
    description: >
      Welcome to Hack New Haven at the University of New Haven! This is the premier hackathon for the region.
      Join us for a weekend of innovation and collaboration as we explore the theme of 
      reaching for new heights in technology and beyond.

  # Info Sections
  info:
    sections:
      - image: "./images/telescope.png"
        title: "LEARN."
        description: >
          Expand your skills, and tackle real-world challenges.
      - image: "images/moon.png"
        title: "BUILD."
        description: >
          Dare to dream, code to innovate with us!
      - image: "images/rocket.png"
        title: "SHARE."
        description: >
          Connect with like-minded individuals.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at the University of New Haven, West Haven, CT.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
